// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
/// 
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDCrirBIPmUMyy3Wq75OoAw5hoUwyi6nh0',
    appId: '1:887967819574:web:e960738a879a97954c3597',
    messagingSenderId: '887967819574',
    projectId: 'drip-flush',
    authDomain: 'drip-flush.firebaseapp.com',
    databaseURL: 'https://drip-flush-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'drip-flush.firebasestorage.app',
    measurementId: 'G-PYP4TCMVPX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBVCopMjdu0MRlx-pNJNSiOSMYJrwFR5Pw',
    appId: '1:887967819574:android:7690ba94977f6c744c3597',
    messagingSenderId: '887967819574',
    projectId: 'drip-flush',
    databaseURL: 'https://drip-flush-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'drip-flush.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAx-ua31gNfIcV-9oVzYnLmdNso-FR8hkI',
    appId: '1:887967819574:ios:d9a2dd27d03051544c3597',
    messagingSenderId: '887967819574',
    projectId: 'drip-flush',
    databaseURL: 'https://drip-flush-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'drip-flush.firebasestorage.app',
    iosBundleId: 'com.example.dripFlush',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAx-ua31gNfIcV-9oVzYnLmdNso-FR8hkI',
    appId: '1:887967819574:ios:d9a2dd27d03051544c3597',
    messagingSenderId: '887967819574',
    projectId: 'drip-flush',
    databaseURL: 'https://drip-flush-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'drip-flush.firebasestorage.app',
    iosBundleId: 'com.example.dripFlush',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDCrirBIPmUMyy3Wq75OoAw5hoUwyi6nh0',
    appId: '1:887967819574:web:a902cb606fad21814c3597',
    messagingSenderId: '887967819574',
    projectId: 'drip-flush',
    authDomain: 'drip-flush.firebaseapp.com',
    databaseURL: 'https://drip-flush-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'drip-flush.firebasestorage.app',
    measurementId: 'G-5ZWQZY8DF5',
  );
}
